const data = {
    products: [
        {
            name: 'Free Shirt',
            category: "Shirts",
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            category: "Shirts",
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.8,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            category: "Shirts",
            image: '/images/shirt3.jpg',
            price: 65,
            brand: 'Raymond',
            rating: 3.9,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            category: "Pants",
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart Looking pants',
        },
        {
            name: 'Fit Pants',
            category: "Pants",
            image: '/images/pants2.jpg',
            price: 70,
            brand: 'Zara',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular pants',
        },
        {
            name: 'Classic Pants',
            category: "Pants",
            image: '/images/pants3.jpg',
            price: 56,
            brand: 'Casely',
            rating: 4.7,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        }
    ]
}

export default data;